---
- name: Validate OS
  ansible.builtin.assert:
    that:
      - "{{ ansible_distribution|lower in ['centos','rocky','alma','rhel'] and (ansible_distribution_major_version|int>=7 and ansible_distribution_major_version|int<=9)}}"

- name: Preparation
  ansible.builtin.include_tasks:
    file: ./preparation.yml

- name: XenOrchestraInstaller
  ansible.builtin.include_tasks:
    file: ./XenOrchestraInstaller.yml

- name: XO cert"
  ansible.builtin.include_tasks:
    file: ./xo-cert.yml

- name: XO-Web banner tweak
  ansible.builtin.include_tasks:
    file: ./xo-web_banner_tweak.yml
  when: xo_web_banner_tweak|default(false)

- name: XO config
  ansible.builtin.include_tasks:
    file: ./xo-config.yml